# Generated by Django 5.2.4 on 2025-08-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='cycle_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
